package cr.ac.una.prograiv.agenda.domain;
// Generated Oct 14, 2017 2:47:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String correo;
     private Usuario usuario;
     private String nombre;
     private String apelllido1;
     private String apellido2;
     private Date fechaNacimiento;
     private String direccion;
     private String telefono;
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public Cliente() {
    }

	
    public Cliente(String correo, Usuario usuario) {
        this.correo = correo;
        this.usuario = usuario;
    }
    public Cliente(String correo, Usuario usuario, String nombre, String apelllido1, String apellido2, Date fechaNacimiento, String direccion, String telefono, Set<Servicio> servicios) {
       this.correo = correo;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apelllido1 = apelllido1;
       this.apellido2 = apellido2;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.telefono = telefono;
       this.servicios = servicios;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApelllido1() {
        return this.apelllido1;
    }
    
    public void setApelllido1(String apelllido1) {
        this.apelllido1 = apelllido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


