package cr.ac.una.prograiv.agenda.domain;
// Generated Oct 14, 2017 2:47:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String idVehiculo;
     private String ubicacionActual;
     private Integer ano;
     private String modelo;
     private Integer placa;
     private String color;
     private Boolean estado;
   // private Set<Conductor> conductors = new HashSet<Conductor>(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public Vehiculo(String idVehiculo, String ubicacionActual, Integer ano, String modelo, Integer placa, String color, Boolean estado){//, Set<Conductor> conductors) {
       this.idVehiculo = idVehiculo;
       this.ubicacionActual = ubicacionActual;
       this.ano = ano;
       this.modelo = modelo;
       this.placa = placa;
       this.color = color;
       this.estado = estado;
      // this.conductors = conductors;
    }
    
 
   
    public String getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getUbicacionActual() {
        return this.ubicacionActual;
    }
    
    public void setUbicacionActual(String ubicacionActual) {
        this.ubicacionActual = ubicacionActual;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Integer getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(Integer placa) {
        this.placa = placa;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
//    public Set<Conductor> getConductors() {
//        return this.conductors;
//    }
//    
//    public void setConductors(Set<Conductor> conductors) {
//        this.conductors = conductors;
//    }




}


